package AllFiles;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author pc
 */
public class LogginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LogginFrame
     */
    public LogginFrame() {
        initComponents();
        getContentPane().setBackground(new Color(204, 255, 204));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        LogginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(new java.awt.Color(204, 255, 204));
        setResizable(false);

        welcomeLabel.setBackground(new java.awt.Color(102, 153, 0));
        welcomeLabel.setFont(new java.awt.Font("Modak", 0, 48)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(102, 153, 0));
        welcomeLabel.setText("Welcome To textIn");

        LogginButton.setBackground(new java.awt.Color(153, 255, 153));
        LogginButton.setFont(new java.awt.Font("Luminari", 0, 36)); // NOI18N
        LogginButton.setForeground(new java.awt.Color(102, 153, 0));
        LogginButton.setText("Login");
        LogginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 0), 3, true));
        LogginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogginButtonActionPerformed(evt);
            }
        });

        SignUpButton.setBackground(new java.awt.Color(153, 255, 153));
        SignUpButton.setFont(new java.awt.Font("Luminari", 0, 36)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(102, 153, 0));
        SignUpButton.setText("SignUp");
        SignUpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 0), 3, true));
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(LogginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
        SignUpClient signup;
        String username = JOptionPane.showInputDialog(null, "Enter Your User Name.");
        String choice = JOptionPane.showInputDialog(null, "1)Generate autopassword.\n2)Make Password.\nEnter Your coice in given textField..");
        while(true){
            if(choice.equals("1")){
                signup=new SignUpClient(username,5001);
                break;
            }
            else if(choice.equals("2")){
                String password=JOptionPane.showInputDialog(null,"Enter Your Password.");
                signup=new SignUpClient(username,password,5001);
                break;
            }
            else
                JOptionPane.showMessageDialog(null, "Invalid choice.");
            choice = JOptionPane.showInputDialog(null, "1)Generate autopassword.\n2)Make Password.\nEnter Your coice in given textField..");
        }
        if(signup.writeUserNamePassInFile()){
            JOptionPane.showMessageDialog(null, "SignUp Succesfull.");
            JOptionPane.showMessageDialog(null, "Your user name is "+signup.getUsername());
            JOptionPane.showMessageDialog(null, "Your password is "+signup.getPassword());
            JOptionPane.showMessageDialog(null, "Your userID is "+SignUpClient.getuserID());
            MessageClient messageClient=new MessageClient(12345);
            messageClient.sendMessageToServer(SignUpClient.getuserID());
            MainFrame mainFrame=new MainFrame();
            mainFrame.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void LogginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogginButtonActionPerformed
        //TODO add your handling code here:
        for(int i=0;i<3;i++){
            String username = JOptionPane.showInputDialog(null, "Enter Your User Name.");
            String password=JOptionPane.showInputDialog(null,"Enter Your Password.");
            String userID=JOptionPane.showInputDialog(null,"Enter Your userID.");
            LogginClient loggin=new LogginClient(username,password,userID,5001);
            if(loggin.checkUserNamePassword()){
                JOptionPane.showMessageDialog(null, "Loggin Succesfull.");
                MessageClient messageClient=new MessageClient(12345);
                messageClient.sendMessageToServer(userID);
                MainFrame mainFrame=new MainFrame();
                mainFrame.setVisible(true);
                this.setVisible(false);
                break;
            }
            else if(i==2){
                JOptionPane.showMessageDialog(null, "Loggin Fail.");
                continue;
            }
            JOptionPane.showMessageDialog(null, "Loggin Fail.Plz Try Again.");
        }
    }//GEN-LAST:event_LogginButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogginButton;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
    private boolean checker;
    public boolean getchecker(){
        return checker;
    }
}
