/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AllFiles;

import java.awt.Color; 
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
//                serialize.Serialization(contactList);
                serialize.Serialization(contactHandler);
            }
        });
        serialize=new Serialize("Contact.rar");
        if(SignUpClient.getuserID()!=null){
//            contactList=new ArrayList<Contact>();
            contactHandler=new ContactHandler();
        }
        else{
//            contactList=(ArrayList<Contact>)serialize.Deserialization();
            contactHandler=(ContactHandler)serialize.Deserialization();
            for(Contact c:contactHandler.getContacts()){
                if (!(ChatHistoryPanel.getLayout() instanceof javax.swing.BoxLayout)) {
                    ChatHistoryPanel.setLayout(new javax.swing.BoxLayout(ChatHistoryPanel, javax.swing.BoxLayout.Y_AXIS));
                }
                ContactButton cb=new ContactButton(c,new javax.swing.ImageIcon(getClass().getResource("/images/Profile.png")));
                ChatHistoryPanel.add(cb);
                ChatHistoryPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 5))); 
                ChatHistoryPanel.revalidate();
                ChatHistoryPanel.repaint();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChatHistoryHeadingPanel = new javax.swing.JPanel();
        chl = new javax.swing.JLabel();
        Settingp = new javax.swing.JPanel();
        AddNewContactButton = new javax.swing.JButton();
        SettingButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChatHistoryPanel = new javax.swing.JPanel();
        MainFrameMainMessagingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ChatHistoryHeadingPanel.setBackground(new java.awt.Color(204, 255, 204));
        ChatHistoryHeadingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0), 3));
        ChatHistoryHeadingPanel.setForeground(new java.awt.Color(102, 102, 0));

        chl.setFont(new java.awt.Font("Kohinoor Devanagari", 1, 24)); // NOI18N
        chl.setForeground(new java.awt.Color(102, 153, 0));
        chl.setIcon(new javax.swing.ImageIcon("/Users/pc/Desktop/cLogo_2-removebg-preview.png")); // NOI18N
        chl.setText("Chat History");

        javax.swing.GroupLayout ChatHistoryHeadingPanelLayout = new javax.swing.GroupLayout(ChatHistoryHeadingPanel);
        ChatHistoryHeadingPanel.setLayout(ChatHistoryHeadingPanelLayout);
        ChatHistoryHeadingPanelLayout.setHorizontalGroup(
            ChatHistoryHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChatHistoryHeadingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chl, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addContainerGap())
        );
        ChatHistoryHeadingPanelLayout.setVerticalGroup(
            ChatHistoryHeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatHistoryHeadingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Settingp.setBackground(new java.awt.Color(102, 153, 0));

        AddNewContactButton.setBackground(new java.awt.Color(204, 255, 204));
        AddNewContactButton.setFont(new java.awt.Font("Kailasa", 1, 13)); // NOI18N
        AddNewContactButton.setForeground(new java.awt.Color(102, 153, 0));
        AddNewContactButton.setText("Add new Contact");
        AddNewContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewContactButtonActionPerformed(evt);
            }
        });

        SettingButton.setBackground(new java.awt.Color(204, 255, 204));
        SettingButton.setFont(new java.awt.Font("Kailasa", 1, 13)); // NOI18N
        SettingButton.setForeground(new java.awt.Color(102, 153, 0));
        SettingButton.setText("Setting");

        javax.swing.GroupLayout SettingpLayout = new javax.swing.GroupLayout(Settingp);
        Settingp.setLayout(SettingpLayout);
        SettingpLayout.setHorizontalGroup(
            SettingpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingpLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AddNewContactButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SettingButton)
                .addGap(55, 55, 55))
        );
        SettingpLayout.setVerticalGroup(
            SettingpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SettingpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddNewContactButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SettingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        ChatHistoryPanel.setBackground(new java.awt.Color(204, 255, 204));
        ChatHistoryPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 0), 3));

        javax.swing.GroupLayout ChatHistoryPanelLayout = new javax.swing.GroupLayout(ChatHistoryPanel);
        ChatHistoryPanel.setLayout(ChatHistoryPanelLayout);
        ChatHistoryPanelLayout.setHorizontalGroup(
            ChatHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ChatHistoryPanelLayout.setVerticalGroup(
            ChatHistoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(ChatHistoryPanel);

        MainFrameMainMessagingPanel.setBackground(new java.awt.Color(204, 255, 204));
        MainFrameMainMessagingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 0), 3));

        javax.swing.GroupLayout MainFrameMainMessagingPanelLayout = new javax.swing.GroupLayout(MainFrameMainMessagingPanel);
        MainFrameMainMessagingPanel.setLayout(MainFrameMainMessagingPanelLayout);
        MainFrameMainMessagingPanelLayout.setHorizontalGroup(
            MainFrameMainMessagingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        MainFrameMainMessagingPanelLayout.setVerticalGroup(
            MainFrameMainMessagingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ChatHistoryHeadingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Settingp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MainFrameMainMessagingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChatHistoryHeadingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Settingp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MainFrameMainMessagingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewContactButtonActionPerformed
         // TODO add your handling code here:
        String name = JOptionPane.showInputDialog(null, "Enter Contact Name.");
        if (name== null || name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No contact added.");
            return;
        }
        
        String str = JOptionPane.showInputDialog(null, "Enter "+name+" userID");
        int userID = Integer.parseInt(str);

        ContactButton contactButton = new ContactButton(name,userID, new javax.swing.ImageIcon(getClass().getResource("/images/Profile.png")));

        if (!(ChatHistoryPanel.getLayout() instanceof javax.swing.BoxLayout)) {
            ChatHistoryPanel.setLayout(new javax.swing.BoxLayout(ChatHistoryPanel, javax.swing.BoxLayout.Y_AXIS));
        }

        ChatHistoryPanel.add(contactButton);
//        contactList.add(contactButton.getContact());
        contactHandler.addContact(contactButton.getContact());
        
        ChatHistoryPanel.add(Box.createRigidArea(new java.awt.Dimension(0, 5))); // Adds 5px vertical space
        
        ChatHistoryPanel.revalidate();
        ChatHistoryPanel.repaint();

    }//GEN-LAST:event_AddNewContactButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewContactButton;
    private javax.swing.JPanel ChatHistoryHeadingPanel;
    private javax.swing.JPanel ChatHistoryPanel;
    private static javax.swing.JPanel MainFrameMainMessagingPanel;
    private javax.swing.JButton SettingButton;
    private javax.swing.JPanel Settingp;
    private javax.swing.JLabel chl;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private ContactHandler contactHandler;
    private Serialize serialize;
    public static javax.swing.JPanel getMainFrameMainMessagingPanel(){
        return MainFrameMainMessagingPanel;
    }
}
